### PR TITLE
bootstrap: native stylesheet not required

### PR DESCRIPTION
**Pull request by phloxic**

### CODE REVIEW

**Comment by nnarhinen** [comment]
Hmm..  I thought it would be needed for the `is-overlaid` class handling. If it really works it must be because the player root element is moved inside the dialog html.

**Comment by nnarhinen** [comment]
I assume you tested this locally? If yes then feel free to merge.

**Comment by phloxic** [comment]
Works here: https://flowplayer.org/standalone/plugins/overlay-bootstrap.html

**Comment by phloxic** [comment]
I'll find out more when I try to adapt http://demos.flowplayer.org/scripting/overlay-fancybox.html and http://demos.flowplayer.org/scripting/overlay-jquerytools.html

**Pull request merged**
